services:
  motion:
    image: basya-motion
    build: .
    tty: true
    ports:
#      - '8080:8080'
      - '8081:8081'
#    command: "motion &"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime


